name: verify
on: push
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         server: ${{ secrets.MATRIX_SERVER }}
         message: |
            new code commit pushed to repository: **${{ github.event.repository.name }}** <br />
            commit message: **${{ github.event.head_commit.message }}** <br />
            commit sha: **${{ github.sha }}** <br />
            commit overview: **[link](https://github.com/smichard/hugo_website/commits/main)** <br />
            project website: **[link](https://dev.michard.io)**