name: verify
on: push
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         server: ${{ secrets.MATRIX_SERVER }}
         message: |
            Hello, world - mes: ${{ github.event.head_commit.message }} - rep name: ${{ github.event.repository.name }} - sha: ${{ github.sha }} - commit overview [Link](https://github.com/smichard/hugo_website/commits/main) - website [link](https://dev.michard.io)