name: verify
on: push
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         server: ${{ secrets.MATRIX_SERVER }}
         message: |
            Hello, world - ${{ github.event.head_commit.message }} - ${{ github.head_ref }} - ${{ github.sha }}